version: '3'
services:
  instapy:
    build: /docker/dev/instapy-docker/
    container_name: instapy
    env_file: /docker/.env
    environment:
      - PYTHONUNBUFFERED=0
      - INSTAPY_WORKSPACE=/code/InstaPy
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/dev/instapy-docker/docker-compose:/code